### ISSUE TITLE
Where to specify map API key?

### ISSUE THREAD

**Issue by gybemark** [angryziber/picasa-gallery#14]
Hi, this is perfect except that the map on the right doesn't display for me.
When I look in the js console I see "js:34 Google Maps API error: MissingKeyMapError ".
I've obtained a browser key in the google api console, but can't see where to specify it in this project?
Sorry if I'm being stupid.

**Comment by angryziber** [comment]
Thanks for the reminder, you can now specify it in config.properties

**Comment by gybemark** [comment]
Excellent, thanks!
