### ISSUE TITLE
clarify "find your newly uploaded album in your Google+ profile"

### ISSUE THREAD

**Issue by amc1804** [angryziber/picasa-gallery#16]
The README says "find your newly uploaded album in your Google+
profile".  How, exactly?  Is that still possible?  "Google+ profile" is
a link to https://plus.google.com/+AntonKeks/photos , but that URL just
redirects to https://plus.google.com/+AntonKeks (and similarly for my
own profile).

Are you still able to add new albums to your public gallery at
https://photos.azib.net/anton.keks ?  If so, how, exactly?

Thanks!
AMC

**Comment by angryziber** [comment]
With the closure of Picasa API, this is no longer possible.
The new Google Photos API requires the user to be authenticated and the new way to make albums visible is to create local content directory
