### ISSUE TITLE
What do you think about separating search url from album urls?

### ISSUE THREAD

**Issue by ido-ran** [angryziber/picasa-gallery#5]
Currently, if I understand correctly, you are not creating special url for search results.
If I happen to have album with ID 2012 and I search for 2012 I get the album and not all photos match "2012" search query.
It just so happen that in my gallery there is album with ID 2012 :)

What do you think about created specific URL for search such as /search/<query> so it will be clear when the site should search in the gallery and when to present an album?

**Comment by angryziber** [comment]
Seems to be obsolete, as search is no longer supported by Google Photos API
