### ISSUE TITLE
[Idea] Filter Albums

### ISSUE THREAD

**Issue by ido-ran** [angryziber/picasa-gallery#6]
In my gallery there are many (over 100) albums and we keep on adding more.
When I show the application to the person responsible for the photo gallery he assume that the search box in the homepage will search for albums.
I've thought about it and realize there are two different searches, but I'm not sure how to present them to the user:

1) simple album filter - When presenting the list of albums allow the user to filter them, on-the-fly, as they type. This can be done client side only because all the information is available.

2) advanced search - This use Google Picasa API to run search. This must be done via the server because the information is simply not exist on the client.

I don't want to have two search boxes or two search buttons because then the UI already fail in term of "Don't make me think" (if you read the book).

What do you think?

**Comment by angryziber** [comment]
Seems to be obsolete
